добавление тестов для ValueObject'ов
EpicCodeCrafters/dance-cup-api pull request #14
Opened 2024-10-10 14:34 UTC by KapikPro

добавление тестов для ValueObject'ов

2024-10-10 18:29 UTC, Zisrf requested changes

2024-10-10 18:29 UTC, Zisrf commented on tests/ECC.DanceCup.Api.Domain.Tests/Model/ValueObjects/CategoryIdTests.cs
> +        var categoryId= CategoryId.From(value);
```suggestion
        var categoryId = CategoryId.From(value);
```

2024-10-10 18:29 UTC, Zisrf commented on tests/ECC.DanceCup.Api.Domain.Tests/Model/ValueObjects/RefereeIdTests.cs
> +        var refereeid = RefereeId.From(value);
```suggestion
        var refereeId = RefereeId.From(value);
```

2024-10-10 18:29 UTC, Zisrf commented on tests/ECC.DanceCup.Api.Domain.Tests/Model/ValueObjects/RefereeIdTests.cs
> +        var refereeid = RefereeId.From(value);
```suggestion
        var refereeId = RefereeId.From(value);
```

2024-10-10 18:29 UTC, Zisrf commented on tests/ECC.DanceCup.Api.Domain.Tests/Model/ValueObjects/UserIdTests.cs
> +        var user = UserId.From(value);
```suggestion
        var userId = UserId.From(value);
```

2024-10-11 07:47 UTC, Zisrf requested changes

2024-10-11 07:47 UTC, Zisrf commented on tests/ECC.DanceCup.Api.Domain.Tests/Model/ValueObjects/TournamentDateTests.cs
> +    public void Create_ShouldContainOnlyDate()
```suggestion
    [Fact]
    public void Create_ShouldContainOnlyDate()
```

2024-10-11 09:43 UTC, KapikPro commented on tests/ECC.DanceCup.Api.Domain.Tests/Model/ValueObjects/TournamentDateTests.cs
> +    public void Create_ShouldContainOnlyDate()
это че и зачем?

2024-10-11 09:44 UTC, Zisrf commented on tests/ECC.DanceCup.Api.Domain.Tests/Model/ValueObjects/TournamentDateTests.cs
> +    public void Create_ShouldContainOnlyDate()
Это атрибут теста, как Theory

2024-10-11 09:45 UTC, Zisrf commented on tests/ECC.DanceCup.Api.Domain.Tests/Model/ValueObjects/TournamentDateTests.cs
> +    public void Create_ShouldContainOnlyDate()
Без него тест не запускается

2024-10-11 09:51 UTC, Zisrf approved these changes

2024-10-11 09:54 UTC, merged