Get referees
EpicCodeCrafters/dance-cup-api pull request #27
Opened 2024-10-28 19:37 UTC by KapikPro

2024-11-03 17:45 UTC, Zisrf requested changes

2024-11-03 17:45 UTC, Zisrf commented on src/ECC.DanceCup.Api.Application.Abstractions/Storage/DomainModel/FancellationToken.cs
> +    public class FancellationToken
Прикольно

2024-11-03 21:42 UTC, KapikPro commented on src/ECC.DanceCup.Api.Application.Abstractions/Storage/DomainModel/FancellationToken.cs
> +    public class FancellationToken
согласен

2024-11-04 19:41 UTC, Zisrf requested changes

2024-11-04 19:41 UTC, Zisrf commented on src/ECC.DanceCup.Api.Application/UseCases/GetReferees/Handler.cs
> +            var referees = await _refereeViewRepository.FindAllAsync(query.RefereeFullName, query.PageNumber,query.PageSize, cancellationToken);
```suggestion
            var referees = await _refereeViewRepository.FindAllAsync(query.RefereeFullName, query.PageNumber, query.PageSize, cancellationToken);
```

2024-11-04 19:41 UTC, Zisrf commented on src/ECC.DanceCup.Api.Presentation.Grpc/DanceCupApiGrpcService.cs
> +
удоли

2024-11-04 19:45 UTC, Zisrf approved these changes
┳━┳ ノ( ゜-゜ノ)

2024-11-04 19:45 UTC, merged