Сохранение агрегата турнира
EpicCodeCrafters/dance-cup-api pull request #30
Opened 2024-11-22 18:13 UTC by KapikPro

- [ ]  проснулся
- [x] потянулся
- [x] пострадал за сетями
- [x] поиграл в комп
- [x] покушал
- [x] сел работать

2024-11-22 18:17 UTC, Zisrf requested changes

2024-11-22 18:17 UTC, Zisrf commented on src/ECC.DanceCup.Api.Infrastructure.Storage/Migrations/00004_Add_Tournaments.cs
> +            "state" int not null,
```suggestion
            "state" text not null,
```

Давай хранить текстом

2024-11-22 18:17 UTC, Zisrf commented on src/ECC.DanceCup.Api.Infrastructure.Storage/Migrations/00004_Add_Tournaments.cs
> +            "finished_at" timestamp
```suggestion
            "registration_started_at" timestamp null,
            "registration_finished_at" timestamp null,
            "started_at" timestamp null,
            "finished_at" timestamp null
```

Модно явно указать

2024-11-22 18:17 UTC, Zisrf commented on src/ECC.DanceCup.Api.Infrastructure.Storage/Migrations/00003_Add_Referees.cs
> +        // language=SQL
нинада :]

2024-11-23 21:18 UTC, Zisrf commented on src/ECC.DanceCup.Api.Infrastructure.Storage/Migrations/00003_Add_Referees.cs
> +        // language=SQL
нифига на зарезолвлено (╬▔皿▔)╯

2024-11-27 20:51 UTC, Zisrf commented on src/ECC.DanceCup.Api.Infrastructure.Storage/Migrations/00006_Add_Couples.cs
> +        """;
```suggestion
        """        
        create table "couples"(
            "id" bigserial primary key,
            "tournament_id" bigint not null,
            "first_participant_full_name" text not null,
            "second_participant_full_name" text null,
            "dance_organization_name" text null,
            "first_trainer_full_name" text null,
            "second_trainer_full_name" text null
        );
        
        create sequence "couples_ids_seq";
        """;
```

2025-01-26 17:04 UTC, KapikPro commented on src/ECC.DanceCup.Api.Infrastructure.Storage/Migrations/00006_Add_Couples.cs
> +        """;
fixed

2025-02-01 12:48 UTC, Zisrf requested changes

2025-02-01 12:48 UTC, Zisrf commented on src/ECC.DanceCup.Api.Application/UseCases/CreateTournament/Handler.cs
> +using ECC.DanceCup.Api.Domain.Model.TournamentAggregate;
Зачем?

2025-02-01 12:48 UTC, Zisrf commented on src/ECC.DanceCup.Api.Infrastructure.Storage/DomainModel/Dbo/CategoryDbo.cs
> +    public required string Name{ get; set; }
Форматирование

2025-02-01 12:48 UTC, Zisrf commented on src/ECC.DanceCup.Api.Infrastructure.Storage/DomainModel/Dbo/CategoryDbo.cs
> +    public required string Name{ get; set; }
```suggestion
    public long TournamentId { get; set; }
    
    public string Name { get; set; } = string.Empty;
```

В DBO лучше делать не required, а значения по умолчанию, потому что мы можем не получить какое-то поле из бд, и в случае с required всё упадёт

2025-02-01 12:48 UTC, Zisrf commented on src/ECC.DanceCup.Api.Infrastructure.Storage/DomainModel/Mappings/TournamentMapping.cs
> +    }
Можно вынести в CategoryMapping

2025-02-01 12:48 UTC, Zisrf commented on src/ECC.DanceCup.Api.Infrastructure.Storage/DomainModel/Mappings/TournamentMapping.cs
> +                secondTrainerFullName: c.SecondTrainerFullName != null ? CoupleTrainerFullName.From(c.SecondTrainerFullName) : null
CoupleMapping

2025-02-01 12:48 UTC, Zisrf commented on src/ECC.DanceCup.Api.Infrastructure.Storage/DomainModel/Mappings/TournamentMapping.cs
> +                couplesIds: new List<CoupleId>()
CategoryMapping

2025-02-01 12:48 UTC, Zisrf commented on src/ECC.DanceCup.Api.Infrastructure.Storage/Providers/CoupleIdProvider.cs
> +            select nextval("couples_ids_seq")
```suggestion
            select nextval("couples_ids_seq");
```

2025-02-07 21:53 UTC, Zisrf approved these changes

2025-02-07 21:54 UTC, merged